// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Department struct {
	ID        string   `json:"id"`
	Number    string   `json:"number"`
	Name      string   `json:"name"`
	FacultyID string   `db:"faculty_id"`
	Groups    []*Group `json:"groups"`
}

type Faculty struct {
	ID          string        `json:"id"`
	Number      string        `json:"number"`
	Name        string        `json:"name"`
	Departments []*Department `json:"departments"`
}

type Group struct {
	ID       string     `json:"id"`
	Number   string     `json:"number"`
	Course   int        `json:"course"`
	Students []*Student `json:"students"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Student struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Login  string `json:"login"`
	Number string `json:"number"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type GroupsFilter struct {
	DepartmentID *string `json:"departmentID"`
	Course       *int    `json:"course"`
}
